config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  devise_for :users
  get 'static/index'
  get 'static/not_index'
  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :body, :uniqueness => true, :length => { :minimum => 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tweets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [ :username, :age])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :age])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  before_action :authenticate_user!, only: [:not_index]
 

  def index
  end

  def not_index
  end



  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :is_owner, only: [:destroy]
    def index 
        @tweets = Tweet.all
    end

    def new
        @tweet = Tweet.new
    end

    def create
        if user_signed_in?
        @tweet = current_user.tweets.create(tweets_params)
        if @tweet.save
            redirect_to tweets_path   
        else
              render :new 
          end
        else
            redirect_to new_user_session_path
        end
    end

    def destroy
        Tweet.find(params[:id]).destroy
        redirect_to tweets_path
    end


    private
    def tweets_params
        params.require(:tweet).permit(:body)
    end

    def is_owner
        if user_signed_in?
            if current_user.id == Tweet.find(params[:id]).user_id
                return true
            else
                redirect_to tweets_path
            end
         else
            redirect_to tweets_path
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

  <% if @tweet.errors.any? %>
    <div id="error_explanation" >
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </p>
  
  <p>
    <%= f.submit "Tweet" %>
  </p>
<% end %>

app/views/tweets/index.html.erb
<h1> Index Tweets</h1>

<% @tweets.each do |tweet| %>

<p> <%= tweet.body %> by <%= tweet.user.email %></p>
<%= link_to  "Delete", tweet_path(tweet) ,method: :delete%>
<hr/>
<%end%>

<%= link_to  "Sing Up", new_user_registration_path %>
<%= link_to  "Sing In", new_user_session_path %>
<%= link_to  "Sign Out", destroy_user_session_path, method: :delete %>

<%= link_to  "You Acount", edit_user_registration_path %>
<%= link_to  "New Tweet", new_tweet_path %>

app/views/tweets/new.html.erb
<h1> New Tweet</h1>

<%= render "tweets/form"%>